// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSg1_hGe-Tr6w4Ku7SWyjT3XhsWWOea34',
    appId: '1:927877396073:web:722775baa073358ac954f8',
    messagingSenderId: '927877396073',
    projectId: 'social-app-90500',
    authDomain: 'social-app-90500.firebaseapp.com',
    storageBucket: 'social-app-90500.appspot.com',
    measurementId: 'G-1S5E6SVFWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09bAJsQQwr45CVvI6FnGIQMKxjIkUZCA',
    appId: '1:927877396073:android:8cc2961c26219a55c954f8',
    messagingSenderId: '927877396073',
    projectId: 'social-app-90500',
    storageBucket: 'social-app-90500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDMaWtyHfHq8oUd0AV6M1APfz_OLwTdY',
    appId: '1:927877396073:ios:08a5a93ae728dcdfc954f8',
    messagingSenderId: '927877396073',
    projectId: 'social-app-90500',
    storageBucket: 'social-app-90500.appspot.com',
    iosClientId: '927877396073-t6emodidlu1jarag7sd61023qdgb2a4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDMaWtyHfHq8oUd0AV6M1APfz_OLwTdY',
    appId: '1:927877396073:ios:08a5a93ae728dcdfc954f8',
    messagingSenderId: '927877396073',
    projectId: 'social-app-90500',
    storageBucket: 'social-app-90500.appspot.com',
    iosClientId: '927877396073-t6emodidlu1jarag7sd61023qdgb2a4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApplication',
  );
}
